require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CheckupEntriesController do

  # This should return the minimal set of attributes required to create a valid
  # CheckupEntry. As you add validations to CheckupEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "entry_no" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CheckupEntriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all checkup_entries as @checkup_entries" do
      checkup_entry = CheckupEntry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:checkup_entries).should eq([checkup_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested checkup_entry as @checkup_entry" do
      checkup_entry = CheckupEntry.create! valid_attributes
      get :show, {:id => checkup_entry.to_param}, valid_session
      assigns(:checkup_entry).should eq(checkup_entry)
    end
  end

  describe "GET new" do
    it "assigns a new checkup_entry as @checkup_entry" do
      get :new, {}, valid_session
      assigns(:checkup_entry).should be_a_new(CheckupEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested checkup_entry as @checkup_entry" do
      checkup_entry = CheckupEntry.create! valid_attributes
      get :edit, {:id => checkup_entry.to_param}, valid_session
      assigns(:checkup_entry).should eq(checkup_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CheckupEntry" do
        expect {
          post :create, {:checkup_entry => valid_attributes}, valid_session
        }.to change(CheckupEntry, :count).by(1)
      end

      it "assigns a newly created checkup_entry as @checkup_entry" do
        post :create, {:checkup_entry => valid_attributes}, valid_session
        assigns(:checkup_entry).should be_a(CheckupEntry)
        assigns(:checkup_entry).should be_persisted
      end

      it "redirects to the created checkup_entry" do
        post :create, {:checkup_entry => valid_attributes}, valid_session
        response.should redirect_to(CheckupEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved checkup_entry as @checkup_entry" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheckupEntry.any_instance.stub(:save).and_return(false)
        post :create, {:checkup_entry => { "entry_no" => "invalid value" }}, valid_session
        assigns(:checkup_entry).should be_a_new(CheckupEntry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheckupEntry.any_instance.stub(:save).and_return(false)
        post :create, {:checkup_entry => { "entry_no" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested checkup_entry" do
        checkup_entry = CheckupEntry.create! valid_attributes
        # Assuming there are no other checkup_entries in the database, this
        # specifies that the CheckupEntry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CheckupEntry.any_instance.should_receive(:update).with({ "entry_no" => "1" })
        put :update, {:id => checkup_entry.to_param, :checkup_entry => { "entry_no" => "1" }}, valid_session
      end

      it "assigns the requested checkup_entry as @checkup_entry" do
        checkup_entry = CheckupEntry.create! valid_attributes
        put :update, {:id => checkup_entry.to_param, :checkup_entry => valid_attributes}, valid_session
        assigns(:checkup_entry).should eq(checkup_entry)
      end

      it "redirects to the checkup_entry" do
        checkup_entry = CheckupEntry.create! valid_attributes
        put :update, {:id => checkup_entry.to_param, :checkup_entry => valid_attributes}, valid_session
        response.should redirect_to(checkup_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the checkup_entry as @checkup_entry" do
        checkup_entry = CheckupEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheckupEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => checkup_entry.to_param, :checkup_entry => { "entry_no" => "invalid value" }}, valid_session
        assigns(:checkup_entry).should eq(checkup_entry)
      end

      it "re-renders the 'edit' template" do
        checkup_entry = CheckupEntry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheckupEntry.any_instance.stub(:save).and_return(false)
        put :update, {:id => checkup_entry.to_param, :checkup_entry => { "entry_no" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested checkup_entry" do
      checkup_entry = CheckupEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => checkup_entry.to_param}, valid_session
      }.to change(CheckupEntry, :count).by(-1)
    end

    it "redirects to the checkup_entries list" do
      checkup_entry = CheckupEntry.create! valid_attributes
      delete :destroy, {:id => checkup_entry.to_param}, valid_session
      response.should redirect_to(checkup_entries_url)
    end
  end

end
